### ISSUE TITLE
Add DSA programs in Java (only).

### ISSUE THREAD

**Issue by MehrotrajiWebsiting** [MehrotrajiWebsiting/JavaDSA#1]

**Comment by scove-viber** [comment]
i'll work on it, please assign me...

**Comment by MehrotrajiWebsiting** [comment]
Ok

**Comment by Sathasivamthirumoorthi** [comment]
please assign me, i would like to work on this

**Comment by pratyushkr11** [comment]
Hi @MehrotrajiWebsiting I would like to work on this issue. Can u please assign me this issue.

**Comment by blieve16** [comment]
Hey @MehrotrajiWebsiting  Please check PR #3 and merge it.

**Comment by MehrotrajiWebsiting** [comment]
Done

**Comment by Sathasivamthirumoorthi** [comment]
Please check your PR

**Comment by pratyushkr11** [comment]
@MehrotrajiWebsiting Can u please add hacktoberfest tag to your repository and PRs so that it can be accepted in hacktoberfest.

**Comment by MehrotrajiWebsiting** [comment]
hacktoberfest tag is already in the repo

**Comment by MehrotrajiWebsiting** [comment]
Thanks for telling

**Comment by amanaggarwal06** [comment]
Hey, please assign it to me.
I want to contribute.

**Comment by Aribaskar-jb** [comment]
please assign me, i would like to work on this

**Comment by MehrotrajiWebsiting** [comment]
Done

**Comment by janvikumariii** [comment]
I would like to work on this

**Comment by ipratham101** [comment]
i would be happy to contribute in this for hacktoberfest 2022

**Comment by MehrotrajiWebsiting** [comment]
Send a pr request to contribute

**Comment by Aribaskar-jb** [comment]
i would be happy to contribute in this for hacktoberfest 2022 on QuickSort in java

please assign me, i would like to work on this

**Comment by MehrotrajiWebsiting** [comment]
Done

**Comment by Aribaskar-jb** [comment]
![image](https://user-images.githubusercontent.com/85920362/199033494-5f33f11f-9d19-4882-b324-67ff5261aa1f.png)
